---
title: "Stat 445 Final"
author: "Amber Duevel"
date: "12/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```

```{r}
MIX = read_xlsx("MIX_model_original_data.xlsx")
MC = read_xlsx("MC_model_original_data.xlsx")

#Notes for MC:
#Dependent Variable: ELISA_microcystin_ugL
#Dependent Variable: ELISA_MC+ANA+SXT

MC_new = MC[!is.na(MC$'ELISA_MC+ANA+SXT'),]
MC_clean = MC_new %>% select_if(~ !any(is.na(.)))
MC_clean$Year = format(as.Date(MC_clean$DateTime, format = "%Y-%m-%d"), "%Y")

MIX_new = MIX[!is.na(MIX$'ELISA_MC+ANA+SXT'),]
MIX_clean = MIX_new %>% select_if(~ !any(is.na(.)))
MIX_clean$Year = format(as.Date(MIX_clean$DateTime, format = "%Y-%m-%d"), "%Y")

MC_clean = MC_clean %>% group_by(Year, siteID)
MC_clean %>% summarise(min(WTemp_C))

MIX$Year = format(as.Date(MIX$DateTime, format = "%Y-%m-%d"), "%Y")

MIX = MIX %>% group_by(Year, siteID)
MIX %>% summarise(median(WTemp_C, na.rm = TRUE))
```

```{r}
MC_clean %>% group_by(Year, siteID) 
Table3 = MC_clean %>% summarise(min(ELISA_anatoxin_ugL), max(ELISA_anatoxin_ugL), median(ELISA_anatoxin_ugL), min(ELISA_microcystin_ugL), max(ELISA_microcystin_ugL), median(ELISA_microcystin_ugL), min(ELISA_saxitoxin_ugL), max(ELISA_saxitoxin_ugL), median(ELISA_saxitoxin_ugL))
view(Table3)
```
